# MySQL Proxy 默认配置
proxy:
  #  frontend-protocol: POSTGRESQL
  port: 7788
  auth:
    user: root
    password: proxy_password
backends:
#  - name: dgp-dsm
#    dialect: POSTGRESQL
#    jdbc-url: jdbc:postgresql://127.0.0.1:5866/dgp-dsm
#    username: highgo
#    password: Highgo@12345
#    max-pool-size: 10
#    min-idle: 2
  - name: dm-dgp-dsm
    dialect: ORACLE
    jdbc-url: jdbc:dm://10.110.60.149:5236?schema=dgp-dsm
    username: SYSDBA
    password: SYSDBA
    max-pool-size: 10
    min-idle: 2
    translation:
      keyword-case: UPPER
      identifier-case: UPPER
translation:
  keyword-case: UPPER
  identifier-case: LOWER
